# External Secrets Operator Configuration for GCP Secret Manager
# This replaces hardcoded secrets with secure Secret Manager integration

apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gcp-secret-store
  namespace: doc-intel-app
spec:
  provider:
    gcpsm:
      projectId: doc-intelligence-1758210325
      auth:
        workloadIdentity:
          clusterLocation: asia-south1
          clusterName: doc-intel-gke
          serviceAccountRef:
            name: external-secrets-sa

---
# External Secret for OpenAI API Key
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: openai-api-key
  namespace: doc-intel-app
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: gcp-secret-store
    kind: SecretStore
  target:
    name: api-keys
    creationPolicy: Owner
  data:
  - secretKey: OPENAI_API_KEY
    remoteRef:
      key: openai-api-key

---
# External Secret for JWT Secret Key
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: jwt-secret-key
  namespace: doc-intel-app
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: gcp-secret-store
    kind: SecretStore
  target:
    name: api-keys
    creationPolicy: Merge
  data:
  - secretKey: JWT_SECRET_KEY
    remoteRef:
      key: jwt-secret-key

---
# External Secret for MySQL Password
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mysql-password
  namespace: doc-intel-app
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: gcp-secret-store
    kind: SecretStore
  target:
    name: db-credentials
    creationPolicy: Owner
  data:
  - secretKey: MYSQL_PASSWORD
    remoteRef:
      key: mysql-password

---
# Service Account for External Secrets Operator
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-sa
  namespace: doc-intel-app
  annotations:
    iam.gke.io/gcp-service-account: document-intelligence-gke-wi@doc-intelligence-1758210325.iam.gserviceaccount.com
