# /kubernetes/01-secrets.yaml
---
# This ExternalSecret pulls database credentials from AWS Secrets Manager
# and creates a corresponding Kubernetes Secret named 'db-credentials'.
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-credentials
  namespace: doc-intel-app
spec:
  secretStoreRef:
    name: aws-secret-store # Assumes a ClusterSecretStore is configured
    kind: ClusterSecretStore
  target:
    name: db-credentials
  data:
  - secretKey: MYSQL_USER
    remoteRef:
      key: doc-intel/rds-credentials
      property: username
  - secretKey: MYSQL_PASSWORD
    remoteRef:
      key: doc-intel/rds-credentials
      property: password
  - secretKey: MONGODB_USER
    remoteRef:
      key: doc-intel/docdb-credentials
      property: username
  - secretKey: MONGODB_PASSWORD
    remoteRef:
      key: doc-intel/docdb-credentials
      property: password
---
# This ExternalSecret pulls API and JWT keys from AWS Secrets Manager
# and creates a corresponding Kubernetes Secret named 'api-keys'.
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: api-keys
  namespace: doc-intel-app
spec:
  secretStoreRef:
    name: aws-secret-store # Assumes a ClusterSecretStore is configured
    kind: ClusterSecretStore
  target:
    name: api-keys
  data:
  - secretKey: JWT_SECRET_KEY
    remoteRef:
      key: doc-intel/jwt-key
  - secretKey: OPENAI_API_KEY
    remoteRef:
      key: doc-intel/openai-key