# /kubernetes/04-text-extraction-deployment.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: text-extraction-deployment
  namespace: doc-intel-app
spec:
  replicas: 1  # Reduced for practice app
  strategy:
    type: Recreate  # Terminate old pod before creating new one (prevents resource conflicts)
  selector:
    matchLabels:
      app: text-extraction-service
  template:
    metadata:
      labels:
        app: text-extraction-service
    spec:
      containers:
      - name: text-extraction-service
        image: asia-south1-docker.pkg.dev/doc-intelligence-1758210325/document-intelligence-containers/text-extraction-service:IMAGE_TAG
        ports:
        - containerPort: 8001
        env:
        # --- GCP Configuration ---
        - name: GCP_PROJECT_ID
          valueFrom:
            secretKeyRef:
              name: gcp-config
              key: GCP_PROJECT_ID
        - name: GCP_REGION
          valueFrom:
            secretKeyRef:
              name: gcp-config
              key: GCP_REGION
        - name: PUBSUB_TOPIC_NAME
          valueFrom:
            secretKeyRef:
              name: gcp-config
              key: PUBSUB_TOPIC_NAME
        - name: GCS_USER_IMAGES_BUCKET
          valueFrom:
            secretKeyRef:
              name: gcp-config
              key: GCS_USER_IMAGES_BUCKET
        # --- Database and Cache Configuration ---
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: gcp-config
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            secretKeyRef:
              name: gcp-config
              key: REDIS_PORT
        - name: REDIS_DB
          value: "0"
        # --- MongoDB Configuration ---
        - name: MONGODB_HOST
          valueFrom:
            secretKeyRef:
              name: mongodb-credentials
              key: MONGODB_HOST
        - name: MONGODB_PORT
          valueFrom:
            secretKeyRef:
              name: mongodb-credentials
              key: MONGODB_PORT
        - name: MONGODB_USER
          valueFrom:
            secretKeyRef:
              name: mongodb-credentials
              key: MONGODB_USER
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-credentials
              key: MONGODB_PASSWORD
        # --- Secrets ---
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: api-keys
              key: JWT_SECRET_KEY
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: api-keys
              key: OPENAI_API_KEY
        # Resource limits optimized for t3.medium instances (cost-effective)
        resources:
          requests:
            memory: "256Mi"  # 256 MB RAM
            cpu: "100m"      # 0.1 CPU cores (reduced from 200m)
          limits:
            memory: "512Mi"  # 512 MB RAM (reduced from 1Gi)
            cpu: "500m"      # 0.5 CPU cores (reduced from 800m)
        readinessProbe:
          httpGet:
            path: /extract/health
            port: 8001
          initialDelaySeconds: 30 # Increased for PDF processing setup
          periodSeconds: 10
          timeoutSeconds: 10

---
# ClusterIP Service for Text Extraction Service (internal access)
apiVersion: v1
kind: Service
metadata:
  name: text-extraction-service
  namespace: doc-intel-app
  labels:
    app: text-extraction-service
spec:
  type: ClusterIP
  selector:
    app: text-extraction-service
  ports:
  - port: 8001
    targetPort: 8001
    protocol: TCP
    name: http
