# /kubernetes/07-text-extraction-hpa.yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: text-extraction-service-hpa
  namespace: doc-intel-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: text-extraction-deployment
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70