# /kubernetes/08-text-summarisation-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: text-summarisation-deployment
  namespace: doc-intel-app
spec:
  replicas: 1  # Reduced for practice app # Run two workers for high availability
  selector:
    matchLabels:
      app: text-summarisation-service
  template:
    metadata:
      labels:
        app: text-summarisation-service
    spec:
      containers:
      - name: text-summarisation-service
        image: asia-south1-docker.pkg.dev/doc-intelligence-1758210325/document-intelligence-containers/text-summarization-service:latest
        ports:
        - containerPort: 8002 # For health check
        env:
        # --- GCP Configuration ---
        - name: GCP_PROJECT_ID
          valueFrom:
            secretKeyRef:
              name: gcp-config
              key: GCP_PROJECT_ID
        - name: GCP_REGION
          valueFrom:
            secretKeyRef:
              name: gcp-config
              key: GCP_REGION
        - name: PUBSUB_SUBSCRIPTION_NAME
          valueFrom:
            secretKeyRef:
              name: gcp-config
              key: PUBSUB_SUBSCRIPTION_NAME
        # --- Secrets ---
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: api-keys
              key: OPENAI_API_KEY
        # Resource requests for lightweight deployment
        resources:
          requests:
            cpu: "100m"      # 0.1 CPU cores
            memory: "256Mi"  # 256 MB RAM
          limits:
            cpu: "500m"      # Max 0.5 CPU cores
            memory: "512Mi"  # Max 512 MB RAM
        # Health checks for the worker
        livenessProbe:
          httpGet:
            path: /health
            port: 8002
          initialDelaySeconds: 30
          periodSeconds: 15