# NodePort Services for GCP Ingress Compatibility
# GCP Ingress requires NodePort or LoadBalancer services (not ClusterIP)

---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: doc-intel-app
  labels:
    app: auth-service
  annotations:
    # Enable NEG for NodePort services used by ingress
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: NodePort
  selector:
    app: auth-service
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http

---
apiVersion: v1
kind: Service
metadata:
  name: text-extraction-service
  namespace: doc-intel-app
  labels:
    app: text-extraction-service
  annotations:
    # Enable NEG for NodePort services used by ingress
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: NodePort
  selector:
    app: text-extraction-service
  ports:
  - port: 8001
    targetPort: 8001
    protocol: TCP
    name: http

---
apiVersion: v1
kind: Service
metadata:
  name: text-summarization-service
  namespace: doc-intel-app
  labels:
    app: text-summarisation-service
  annotations:
    # Remove any LoadBalancer annotations for ClusterIP services
    cloud.google.com/neg: '{"ingress": false}'
spec:
  type: NodePort
  selector:
    app: text-summarisation-service
  ports:
  - port: 8002
    targetPort: 8002
    protocol: TCP
    name: http
